services:
  - type: web
    name: kudo-tv-bot
    runtime: python
    repo: https://github.com/iroennys-admin/kudo-tv-bot
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    healthCheckPath: /
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        value: KudoTVBot
      - key: ADMIN_IDS
        value: "[6438282268]"
      - key: GRUPO_ESTRENOS
        value: "https://t.me/+placeholder"
      - key: GRUPO_ESTRENOS_ID
        value: "-100"
      - key: CANAL_PRIVADO_ID
        sync: false
      - key: CANAL_DESTINO_ID
        sync: false
